### PR TITLE
Limit output of tSQLt.AssertTableEuqlas to 20 rows

### PR DESCRIPTION
**Pull request by TheConstructor**
For very long comparison results formatting takes ages. To work around the problem alter tSQLt.Private_CompareTables to remove rows in excess of a ("random") 20-row limit and adds a row with the match-indicator "?".

We ran into the problem when a source table was changed and more than 200 rows were detected as different. The build that previously finished within one hour now took more than 9 hours, which was the time-limit assigned to it. Applying this change we are back to under 1 hour.

While I know that this is not an optimal solution (no way to set limit, no communication how many rows were removed), I do think, that limiting the number of changed rows does not reduce usefulness of the tests. Feel free to improve upon my solution.

? was chosen as in our collate it sorts below <=>.

### CODE REVIEW

**Comment by lizbaron** [comment]
Hi Matthias,

Thank you for this suggestion. Writing unit tests that use hundreds of rows of test data tends to make it very difficult to maintain test suites. A best practice in unit testing is to create only enough test data in each test to test the functionality.

We can't approve this pull request because it may be a breaking change for other users.

Thanks again for your contribution.

**Comment by TheConstructor** [comment]
Hi @lizbaron,

I know that you should keep test-data as sparse as possible, but especially when things go wrong it may yield bigger than expected results. You may have seen that I order so, that outputting differences is preferred over outputting equal lines. While certainly this changes things and it's debatable whether 20 is the right number (configuration?) I doubt that hundreds of lines output regularly help in finding the culprit. Worse: they take ages to be generated and captured.

Please reconsider this pull request, or tell me if you see another chance of solving my problem.

Thank you.

**Comment by TheConstructor** [comment]
One can surely work around this, but tests where you want to ensure e.g. that something only deleted/updated the right procedure tends to work with an unfaked table (sys.objects, ...). Outputting all the unchanged lines does not really help in this case.

**Comment by dkultasev** [comment]
What about an idea to have some kind of configuration where default value would be to show all output and it can be changed if needed?
That won't break any existing functionality and allow to reduce this "noise"

**Comment by mbt1** [comment]
What I could see as an option is to limit the output on a test by test basis. 

We could use the new annotation framework for that:

`--[@tSQLt:TableOutputFilter](@Filter)`

With `@Filter` accepting the values

  - all()
  - different()
  - top(???)

The top option would need to apply to AssertEmptyTable, too. 

The fact that rows were omitted from the result should probably be printed out (in addition to the "?" row).

Thoughts?

**Comment by TheConstructor** [comment]
Would definitely help. I was primarily thinking of 'guarding' our nightly build though. I would argue, that in our nightly builds the information that a test is failing is way more important than having all details. I employed my modification to have our nightly finish at night - which they were not before.

So I would love to hav a way to globally limit the output and then be able to increase the output when a developer investigates the failing test (where probably a regular result set still performs way better).

**Comment by mbt1** [comment]
I am wary about documenting a feature that encourages "out of design" use of the framework. However,  I could see an option to change the default behavior by setting a global `TableOutputFilter` similar to the `TestResultFormatter` that already exists.

Each filter should be a procedure that will be called to "filter" the rows in the output based on its rules.

Something like:

`tSQLt.TableOutputFilterAll @ResultTable NVARCHAR(MAX), @ResultColumn NVARCHAR(MAX), @ColumnList NVARCHAR(MAX)`

`tSQLt.TableOutputFilterDifferent @ResultTable NVARCHAR(MAX), @ResultColumn NVARCHAR(MAX), @ColumnList NVARCHAR(MAX)`

`tSQLt.TableOutputFilterTop @RowCount INT, @ResultTable NVARCHAR(MAX), @ResultColumn NVARCHAR(MAX), @ColumnList NVARCHAR(MAX)`

`@ColumnList` might not be needed, but the interface should be the same across all of them, with additional required parameters (like `@RowCount` coming first.


If you take this on, we do need adequate test coverage to accept the PR.

**Comment by TheConstructor** [comment]
@mbt1 I created #67 as I suspect this to take some time and it might be a better place to clarify stuff.

**Pull request closed without merging**
