### PR TITLE
Removing PARSENAME from sys.schemas lookup in DropClass procedure

### PR DESCRIPTION
**Pull request by Prof-hu**
Proposed solution to issue [https://github.com/tSQLt-org/tSQLt/issues/5](https://github.com/tSQLt-org/tSQLt/issues/5)

### CODE REVIEW

**Comment by mbt1** [comment]
Implementing this would change documented behavior and potentially break many tests for other tSQLt users.

**Comment by Prof-hu** [comment]
What is the exact behavior that is referenced here? Can you point me to that section in the documentation?

**Comment by mbt1** [comment]
The expected behavior is that you can pass in names with and without brackets. The PARSENAME function is the only reliable way to remove those brackets for further processing. Your other comment however tells me that there is a test missing. I will look into that.

**Comment by Prof-hu** [comment]
@mbt1 
> The expected behavior is that you can pass in names with and without brackets. The PARSENAME function is the only reliable way to remove those brackets for further processing. Your other comment however tells me that there is a test missing. I will look into that.

I see. Then probably PARSENAME should be used at all the other WHERE clauses. It would still not work with a schema name with a dot in it supplied without brackets, but at least would work with brackets. :D

**Pull request closed without merging**
